

CREATE TABLE DUTY_CONFIG (DUTY_CONFIG_ID NUMBER NOT NULL, DUTY_CONFIG_NAME VARCHAR2(32), DUTY_HANDOVER_TYPE VARCHAR2(32), DUTY_HANDOVER_TIME VARCHAR2(32), LAST_DUTY_CONFIG_ID NUMBER, CREATE_TIME VARCHAR2(32), CONSTRAINT DUTY_CONFIG_ID PRIMARY KEY (DUTY_CONFIG_ID));
COMMENT ON COLUMN DUTY_CONFIG.DUTY_CONFIG_ID IS '值班id';
COMMENT ON COLUMN DUTY_CONFIG.DUTY_CONFIG_NAME IS '值班配置名称';
COMMENT ON COLUMN DUTY_CONFIG.DUTY_HANDOVER_TYPE IS '交接班方式';
COMMENT ON COLUMN DUTY_CONFIG.DUTY_HANDOVER_TIME IS '交接班误差时间';
COMMENT ON COLUMN DUTY_CONFIG.LAST_DUTY_CONFIG_ID IS '上一次值班配置id';
COMMENT ON COLUMN DUTY_CONFIG.CREATE_TIME IS '创建时间';


CREATE TABLE DUTY_FLIGHT_CONFIG (DUTY_FLIGHT_ID NUMBER NOT NULL, DUTY_FLIGHT_NAME VARCHAR2(32), DUTY_FLIGHT_BEGINTIME VARCHAR2(32), DUTY_FLIGHT_ENDTIME VARCHAR2(32), DUTY_CONFIG_ID NUMBER, LAST_DUTY_FLIGHT_ID NUMBER, CREATE_TIME VARCHAR2(32), LAST_DUTY_CONFIG_ID NUMBER, CONSTRAINT DUTY_FLIGHT_ID PRIMARY KEY (DUTY_FLIGHT_ID));
COMMENT ON COLUMN DUTY_FLIGHT_CONFIG.DUTY_FLIGHT_ID IS '班次id';
COMMENT ON COLUMN DUTY_FLIGHT_CONFIG.DUTY_FLIGHT_NAME IS '班次名称';
COMMENT ON COLUMN DUTY_FLIGHT_CONFIG.DUTY_FLIGHT_BEGINTIME IS '班次开始时间';
COMMENT ON COLUMN DUTY_FLIGHT_CONFIG.DUTY_FLIGHT_ENDTIME IS '班次结束时间';
COMMENT ON COLUMN DUTY_FLIGHT_CONFIG.DUTY_CONFIG_ID IS '值班配置id';
COMMENT ON COLUMN DUTY_FLIGHT_CONFIG.LAST_DUTY_FLIGHT_ID IS '上一次班次配置id';
COMMENT ON COLUMN DUTY_FLIGHT_CONFIG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DUTY_FLIGHT_CONFIG.LAST_DUTY_CONFIG_ID IS '上一次值班配置id';


create table DUTY_INFO
(
  DUTY_LOG_ID               NUMBER(19) not null,
  CREATE_TIME               DATE,
  CREATE_USER               VARCHAR2(64),
  DEAL_USER                 VARCHAR2(64),
  DEAL_TIME                 DATE,
  MAIN_STATIONS             VARCHAR2(100),
  MAIN_FAULT_SUB_SYSTEM     VARCHAR2(100),
  MAIN_FAULT_EQUIPMENT_TYPE VARCHAR2(100),
  MAIN_FAULT_TYPE           VARCHAR2(100),
  MAIN_FAULT_DESC           VARCHAR2(4000),
  PROCESSING_PROCEDURE      VARCHAR2(4000),
  RESOLVE_IF                VARCHAR2(100),
  ATTENTION_IF              VARCHAR2(100),
  REMAIN_IF                 VARCHAR2(100) default '0',
  MAIN_SUB_CENTER           VARCHAR2(200),
  NOTE                      VARCHAR2(4000)
)
;
comment on column DUTY_INFO.DUTY_LOG_ID
  is '值班记录id';
comment on column DUTY_INFO.CREATE_TIME
  is '创建日期';
comment on column DUTY_INFO.CREATE_USER
  is '记录人';
comment on column DUTY_INFO.DEAL_USER
  is '处理人';
comment on column DUTY_INFO.DEAL_TIME
  is '处理完成时间';
comment on column DUTY_INFO.MAIN_STATIONS
  is '台站';
comment on column DUTY_INFO.MAIN_FAULT_SUB_SYSTEM
  is '子系统';
comment on column DUTY_INFO.MAIN_FAULT_EQUIPMENT_TYPE
  is '设备类型';
comment on column DUTY_INFO.MAIN_FAULT_TYPE
  is '故障类型';
comment on column DUTY_INFO.MAIN_FAULT_DESC
  is '故障描述';
comment on column DUTY_INFO.PROCESSING_PROCEDURE
  is '处理过程';
comment on column DUTY_INFO.RESOLVE_IF
  is '是否解决';
comment on column DUTY_INFO.ATTENTION_IF
  is '特别注意';
comment on column DUTY_INFO.REMAIN_IF
  is '是否遗留';
comment on column DUTY_INFO.MAIN_SUB_CENTER
  is '台站中心';
comment on column DUTY_INFO.NOTE
  is '备注';
alter table DUTY_INFO
  add unique (DUTY_LOG_ID);

CREATE TABLE DUTY_SCHEDULING_USERS (DUTY_ID NUMBER(19) NOT NULL, USERID VARCHAR2(50), USERNAME VARCHAR2(50), DUTY_FLIGHT_ID NUMBER(19), DUTY_CONFIG_ID NUMBER(19), SCHEDULING_ID NUMBER(19), DELETE_IF NUMBER(2), REASON VARCHAR2(500), DUTY_TIME DATE, HEAD_IF NUMBER(1), DUTY_HANDOVER_TYPE VARCHAR2(100),remark VARCHAR2(4000), CONSTRAINT DUTY_ID_PRIMARY_KEY PRIMARY KEY (DUTY_ID));
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.DUTY_ID IS '值班id';
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.USERID IS '人员id';
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.USERNAME IS '人员名称';
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.DUTY_FLIGHT_ID IS '班次id';
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.DUTY_CONFIG_ID IS '值班配置id';
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.SCHEDULING_ID IS '排班id';
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.DELETE_IF IS '是否删除：1:是 0:否';
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.REASON IS '调整原因';
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.DUTY_TIME IS '日期';
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.HEAD_IF IS '是否组长：1:是 0:否';
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.DUTY_HANDOVER_TYPE IS '交接班配置类型：无需交接班,由值班长交接班，任意值班人员交接，所有值班人员都需交接';
COMMENT ON COLUMN DUTY_SCHEDULING_USERS.remark IS '备注';


CREATE TABLE DUTY_SUCCESSION_SHIFT (SHIFT_ID NUMBER NOT NULL, DUTY_CONFIG_ID NUMBER, DUTY_FLIGHT_ID NUMBER, DUTY_TIME DATE, NOW_DUTY_USERID VARCHAR2(300), LAST_DUTY_USERID VARCHAR2(300), NEXT_DUTY_USERID VARCHAR2(300), SUCCESSION_USERID VARCHAR2(300), SHIFT_USERID VARCHAR2(300), SUCCESSION_TIME DATE, SHIFT_TIME DATE, SUCCESSION_IF NUMBER, SHIFT_IF NUMBER, FIRST_TIME DATE,LAST_SHIFT_ID  NUMBER,NOTE VARCHAR2(4000),FINAL_SUCCESSION_TIME DATE,FINAL_SHIFT_TIME DATE, PRIMARY KEY (SHIFT_ID));
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.SHIFT_ID IS '交接班id';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.DUTY_CONFIG_ID IS '值班配置id';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.DUTY_FLIGHT_ID IS '班次id';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.DUTY_TIME IS '值班日期';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.NOW_DUTY_USERID IS '本班次值班人员';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.LAST_DUTY_USERID IS '上班次值班人员';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.NEXT_DUTY_USERID IS '下班次值班人员';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.SUCCESSION_USERID IS '接班人员';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.SHIFT_USERID IS '交班人员';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.SUCCESSION_TIME IS '接班时间';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.SHIFT_TIME IS '交班时间';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.SUCCESSION_IF IS '是否接班1:是 0:否';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.SHIFT_IF IS '是否交班1:是 0:否';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.FIRST_TIME IS '最早交班时间';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.LAST_SHIFT_ID IS '上一班次交接班id';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.NOTE IS '遗留问题及重要通知';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.FINAL_SUCCESSION_TIME IS '最迟接班时间';
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT.FINAL_SHIFT_TIME IS '最迟交班时间';



CREATE TABLE DUTY_SUCCESSION_SHIFT_USER (SHIFT_USER_ID NUMBER NOT NULL, USER_ID VARCHAR2(300), SHIFT_ID NUMBER, SUCCESSION_TIME DATE, SHIFT_TIME DATE, SUCCESSION_IF NUMBER, SHIFT_IF NUMBER, NOTE VARCHAR2(1000),PRIMARY KEY (SHIFT_USER_ID));
COMMENT ON COLUMN DUTY_SUCCESSION_SHIFT_USER.NOTE IS '备注';

CREATE TABLE DUTY_USERS (DUTY_USERS_ID NUMBER NOT NULL, USER_ID VARCHAR2(300), USER_NAME VARCHAR2(300), DUTY_CONFIG_ID NUMBER, CREATE_TIME DATE, PRIMARY KEY (DUTY_USERS_ID));
COMMENT ON COLUMN DUTY_USERS.DUTY_USERS_ID IS '值班人员id';
COMMENT ON COLUMN DUTY_USERS.USER_ID IS '人员id';
COMMENT ON COLUMN DUTY_USERS.USER_NAME IS 'user_name';
COMMENT ON COLUMN DUTY_USERS.DUTY_CONFIG_ID IS '值班配置id';
COMMENT ON COLUMN DUTY_USERS.CREATE_TIME IS '修改时间';

CREATE TABLE DUTY_SHIFT_CENTRALFAULT (SHIFT_ID NUMBER, SHEETID VARCHAR2(100), TITLE VARCHAR2(500), SENDTIME DATE, SHEETCOMPLETELIMIT VARCHAR2(32),MAINALARMCLEARTIME VARCHAR2(32),TASKNAME VARCHAR2(100),TASKSTATUS VARCHAR2(32),TASKOWNER VARCHAR2(50),PREDEALDEPT VARCHAR2(32),PREDEALUSERID VARCHAR2(32) );
COMMENT ON COLUMN DUTY_SHIFT_CENTRALFAULT.SHIFT_ID IS '交接班id';
alter table DUTY_SHIFT_CENTRALFAULT add constraint pk_name primary key (SHEETID,SHIFT_ID);

CREATE TABLE DUTY_SHIFT_ALARMACT (alarm_id VARCHAR2(100), eqp_object_class VARCHAR2(32), eqp_label VARCHAR2(100),
 alarm_title_text VARCHAR2(255), org_severity NUMBER,station_name VARCHAR2(100),event_time Date,subcenter_name VARCHAR2(100), PRIMARY KEY (alarm_id));
COMMENT ON COLUMN DUTY_SHIFT_ALARMACT.alarm_id IS '告警id';
COMMENT ON COLUMN DUTY_SHIFT_ALARMACT.eqp_object_class IS '设备类型';
COMMENT ON COLUMN DUTY_SHIFT_ALARMACT.eqp_label IS '网元名称';
COMMENT ON COLUMN DUTY_SHIFT_ALARMACT.alarm_title_text IS '告警标题';
COMMENT ON COLUMN DUTY_SHIFT_ALARMACT.org_severity IS '告警级别';
COMMENT ON COLUMN DUTY_SHIFT_ALARMACT.station_name IS '台站名称';
COMMENT ON COLUMN DUTY_SHIFT_ALARMACT.event_time IS '告警发生时间';
COMMENT ON COLUMN DUTY_SHIFT_ALARMACT.subcenter_name IS '分中心名称';



create table DUTY_CHANGE_FLIGHT
(
  ID               NUMBER(19) not null,
  CREATE_FLIGHT_ID NUMBER(19),
  CREATE_USER      VARCHAR2(100),
  DEAL_USER        VARCHAR2(100),
  AUDIT_USER       VARCHAR2(100),
  CREATE_DUTY_TIME DATE,
  APPLY_RESULT     VARCHAR2(500),
  STATUS           VARCHAR2(50),
  SHEET_STATUS     NUMBER(10),
  DEAL_FLIGHT_ID   NUMBER(19),
  DEAL_DUTY_TIME   DATE,
  CREATE_TIME      DATE
)
;
comment on column DUTY_CHANGE_FLIGHT.ID
  is '主键ID';
comment on column DUTY_CHANGE_FLIGHT.CREATE_FLIGHT_ID
  is '申请人班次ID';
comment on column DUTY_CHANGE_FLIGHT.CREATE_USER
  is '请求人';
comment on column DUTY_CHANGE_FLIGHT.DEAL_USER
  is '接收人';
comment on column DUTY_CHANGE_FLIGHT.AUDIT_USER
  is '负责人';
comment on column DUTY_CHANGE_FLIGHT.CREATE_DUTY_TIME
  is '申请人值班开始时间';
comment on column DUTY_CHANGE_FLIGHT.APPLY_RESULT
  is '申请原因';
comment on column DUTY_CHANGE_FLIGHT.STATUS
  is '状态（接收人待回复、接收人不同意、审核人审核中、审核人同意、审核人不同意）';
comment on column DUTY_CHANGE_FLIGHT.SHEET_STATUS
  is '工单状态（接收人环节：0，审核人环节：1，申请人环节：2，归档：3）';
comment on column DUTY_CHANGE_FLIGHT.DEAL_FLIGHT_ID
  is '接收人班次ID';
comment on column DUTY_CHANGE_FLIGHT.DEAL_DUTY_TIME
  is '接收人值班开始时间';
comment on column DUTY_CHANGE_FLIGHT.CREATE_TIME
  is '申请时间';
alter table DUTY_CHANGE_FLIGHT
  add primary key (ID);

create table p_remind_user
(
  id               VARCHAR2(32) not null,
  user_id          VARCHAR2(100),
  remind_content   VARCHAR2(2000),
  remind_time      DATE,
  deleted          NUMBER,
  model_type       VARCHAR2(100)
)
;
comment on column p_remind_user.id
  is '主键id';
comment on column p_remind_user.user_id
  is '通知人id';
comment on column p_remind_user.remind_content
  is '通知内容';
comment on column p_remind_user.remind_time
  is '通知时间';
comment on column p_remind_user.model_type
  is '模块类型';
  comment on column p_remind_user.deleted
  is '删除标示';
alter table p_remind_user
  add primary key (id);


  
CREATE SEQUENCE DUTY_CONFIG_SEQ
MINVALUE 1
START WITH 1
NOMAXVALUE
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE DUTY_FLIGHT_CONFIG_SEQ
MINVALUE 1
START WITH 1
NOMAXVALUE
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE DUTY_INFO_SEQ
MINVALUE 1
START WITH 1
NOMAXVALUE
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE DUTY_SCHEDULING_USERS_SEQ
MINVALUE 1
START WITH 1
NOMAXVALUE
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE DUTY_SUCCESSION_SHIFT_SEQ
MINVALUE 1
START WITH 1
NOMAXVALUE
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE DUTY_SUCCESSION_SHIFT_USER_SEQ
MINVALUE 1
START WITH 1
NOMAXVALUE
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE DUTY_USERS_SEQ
MINVALUE 1
START WITH 1
NOMAXVALUE
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE DUTY_SHIFT_CENTRALFAULT_SEQ
MINVALUE 1
START WITH 1
NOMAXVALUE
INCREMENT BY 1
NOCYCLE
NOCACHE;


CREATE SEQUENCE DUTY_CHANGE_FLIGHT_SEQ
MINVALUE 1
START WITH 1
NOMAXVALUE
INCREMENT BY 1
NOCYCLE
NOCACHE;
