package com.boco.eoms.successionShift.model;

import java.util.Date;

/** DUTY_SUCCESSION_SHIFT */
public class SuccessionShiftModel {

	/** DUTY_SUCCESSION_SHIFT.SHIFT_ID */
	private Integer SHIFT_ID;
	/** DUTY_SUCCESSION_SHIFT.DUTY_CONFIG_ID */
	private Integer DUTY_CONFIG_ID;
	/** DUTY_SUCCESSION_SHIFT.DUTY_FLIGHT_ID */
	private Integer DUTY_FLIGHT_ID;
	/** DUTY_SUCCESSION_SHIFT.DUTY_TIME */
	private Date DUTY_TIME;
	/** DUTY_SUCCESSION_SHIFT.NOW_DUTY_USERID */
	private String NOW_DUTY_USERID;
	/** DUTY_SUCCESSION_SHIFT.LAST_DUTY_USERID */
	private String LAST_DUTY_USERID;
	/** DUTY_SUCCESSION_SHIFT.NEXT_DUTY_USERID */
	private String NEXT_DUTY_USERID;
	/** DUTY_SUCCESSION_SHIFT.SUCCESSION_USERID */
	private String SUCCESSION_USERID;
	/** DUTY_SUCCESSION_SHIFT.SHIFT_USERID */
	private String SHIFT_USERID;
	/** DUTY_SUCCESSION_SHIFT.SUCCESSION_TIME */
	private Date SUCCESSION_TIME;
	/** DUTY_SUCCESSION_SHIFT.SHIFT_TIME */
	private Date SHIFT_TIME;
	/** DUTY_SUCCESSION_SHIFT.SUCCESSION_IF */
	private Integer SUCCESSION_IF;
	/** DUTY_SUCCESSION_SHIFT.SHIFT_IF */
	private Integer SHIFT_IF;
	/** DUTY_SUCCESSION_SHIFT.FIRST_TIME */
	private Date FIRST_TIME;
	
	/** DUTY_SUCCESSION_SHIFT.FINAL_SUCCESSION_TIME */
	private Date FINAL_SUCCESSION_TIME;
	
	/** DUTY_SUCCESSION_SHIFT.FINAL_SUCCESSION_TIME */
	private Date FINAL_SHIFT_TIME;
	
	/** DUTY_SUCCESSION_SHIFT.LAST_SHIFT_ID */
	private Integer LAST_SHIFT_ID;

	/** DUTY_SUCCESSION_SHIFT.NOTE */
	private String NOTE;
	
	
	
	public Date getFINAL_SHIFT_TIME() {
		return FINAL_SHIFT_TIME;
	}
	public void setFINAL_SHIFT_TIME(Date fINAL_SHIFT_TIME) {
		FINAL_SHIFT_TIME = fINAL_SHIFT_TIME;
	}
	public Date getFINAL_SUCCESSION_TIME() {
		return FINAL_SUCCESSION_TIME;
	}
	public void setFINAL_SUCCESSION_TIME(Date fINAL_SUCCESSION_TIME) {
		FINAL_SUCCESSION_TIME = fINAL_SUCCESSION_TIME;
	}
	public String getNOTE() {
		return NOTE;
	}
	public void setNOTE(String nOTE) {
		NOTE = nOTE;
	}
	
	/** DUTY_SUCCESSION_SHIFT.SHIFT_ID */
	public Integer getSHIFT_ID() {
		return SHIFT_ID;
	}
	/** DUTY_SUCCESSION_SHIFT.SHIFT_ID */
	public void setSHIFT_ID(Integer SHIFT_ID) {
		this.SHIFT_ID = SHIFT_ID;
	}
	/** DUTY_SUCCESSION_SHIFT.DUTY_CONFIG_ID */
	public Integer getDUTY_CONFIG_ID() {
		return DUTY_CONFIG_ID;
	}
	/** DUTY_SUCCESSION_SHIFT.DUTY_CONFIG_ID */
	public void setDUTY_CONFIG_ID(Integer DUTY_CONFIG_ID) {
		this.DUTY_CONFIG_ID = DUTY_CONFIG_ID;
	}
	/** DUTY_SUCCESSION_SHIFT.DUTY_FLIGHT_ID */
	public Integer getDUTY_FLIGHT_ID() {
		return DUTY_FLIGHT_ID;
	}
	/** DUTY_SUCCESSION_SHIFT.DUTY_FLIGHT_ID */
	public void setDUTY_FLIGHT_ID(Integer DUTY_FLIGHT_ID) {
		this.DUTY_FLIGHT_ID = DUTY_FLIGHT_ID;
	}
	/** DUTY_SUCCESSION_SHIFT.DUTY_TIME */
	public Date getDUTY_TIME() {
		return DUTY_TIME;
	}
	/** DUTY_SUCCESSION_SHIFT.DUTY_TIME */
	public void setDUTY_TIME(Date DUTY_TIME) {
		this.DUTY_TIME = DUTY_TIME;
	}
	/** DUTY_SUCCESSION_SHIFT.NOW_DUTY_USERID */
	public String getNOW_DUTY_USERID() {
		return NOW_DUTY_USERID;
	}
	/** DUTY_SUCCESSION_SHIFT.NOW_DUTY_USERID */
	public void setNOW_DUTY_USERID(String NOW_DUTY_USERID) {
		this.NOW_DUTY_USERID = NOW_DUTY_USERID == null ? null : NOW_DUTY_USERID.trim();
	}
	/** DUTY_SUCCESSION_SHIFT.LAST_DUTY_USERID */
	public String getLAST_DUTY_USERID() {
		return LAST_DUTY_USERID;
	}
	/** DUTY_SUCCESSION_SHIFT.LAST_DUTY_USERID */
	public void setLAST_DUTY_USERID(String LAST_DUTY_USERID) {
		this.LAST_DUTY_USERID = LAST_DUTY_USERID == null ? null : LAST_DUTY_USERID.trim();
	}
	/** DUTY_SUCCESSION_SHIFT.NEXT_DUTY_USERID */
	public String getNEXT_DUTY_USERID() {
		return NEXT_DUTY_USERID;
	}
	/** DUTY_SUCCESSION_SHIFT.NEXT_DUTY_USERID */
	public void setNEXT_DUTY_USERID(String NEXT_DUTY_USERID) {
		this.NEXT_DUTY_USERID = NEXT_DUTY_USERID == null ? null : NEXT_DUTY_USERID.trim();
	}
	/** DUTY_SUCCESSION_SHIFT.SUCCESSION_USERID */
	public String getSUCCESSION_USERID() {
		return SUCCESSION_USERID;
	}
	/** DUTY_SUCCESSION_SHIFT.SUCCESSION_USERID */
	public void setSUCCESSION_USERID(String SUCCESSION_USERID) {
		this.SUCCESSION_USERID = SUCCESSION_USERID == null ? null : SUCCESSION_USERID.trim();
	}
	/** DUTY_SUCCESSION_SHIFT.SHIFT_USERID */
	public String getSHIFT_USERID() {
		return SHIFT_USERID;
	}
	/** DUTY_SUCCESSION_SHIFT.SHIFT_USERID */
	public void setSHIFT_USERID(String SHIFT_USERID) {
		this.SHIFT_USERID = SHIFT_USERID == null ? null : SHIFT_USERID.trim();
	}
	/** DUTY_SUCCESSION_SHIFT.SUCCESSION_TIME */
	public Date getSUCCESSION_TIME() {
		return SUCCESSION_TIME;
	}
	/** DUTY_SUCCESSION_SHIFT.SUCCESSION_TIME */
	public void setSUCCESSION_TIME(Date SUCCESSION_TIME) {
		this.SUCCESSION_TIME = SUCCESSION_TIME;
	}
	/** DUTY_SUCCESSION_SHIFT.SHIFT_TIME */
	public Date getSHIFT_TIME() {
		return SHIFT_TIME;
	}
	/** DUTY_SUCCESSION_SHIFT.SHIFT_TIME */
	public void setSHIFT_TIME(Date SHIFT_TIME) {
		this.SHIFT_TIME = SHIFT_TIME;
	}
	/** DUTY_SUCCESSION_SHIFT.SUCCESSION_IF */
	public Integer getSUCCESSION_IF() {
		return SUCCESSION_IF;
	}
	/** DUTY_SUCCESSION_SHIFT.SUCCESSION_IF */
	public void setSUCCESSION_IF(Integer SUCCESSION_IF) {
		this.SUCCESSION_IF = SUCCESSION_IF;
	}
	/** DUTY_SUCCESSION_SHIFT.SHIFT_IF */
	public Integer getSHIFT_IF() {
		return SHIFT_IF;
	}
	/** DUTY_SUCCESSION_SHIFT.SHIFT_IF */
	public void setSHIFT_IF(Integer SHIFT_IF) {
		this.SHIFT_IF = SHIFT_IF;
	}
	/** DUTY_SUCCESSION_SHIFT.FIRST_TIME */
	public Date getFIRST_TIME() {
		return FIRST_TIME;
	}
	/** DUTY_SUCCESSION_SHIFT.FIRST_TIME */
	public void setFIRST_TIME(Date FIRST_TIME) {
		this.FIRST_TIME = FIRST_TIME;
	}
	public Integer getLAST_SHIFT_ID() {
		return LAST_SHIFT_ID;
	}
	public void setLAST_SHIFT_ID(Integer lAST_SHIFT_ID) {
		this.LAST_SHIFT_ID = lAST_SHIFT_ID;
	}
}